name: Build Windows App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.40.0
          playwright install --with-deps chromium
          pip install pyinstaller==6.12.0

      - name: Create icon file
        run: |
          curl -o icon.ico https://www.google.com/favicon.ico

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico --name="抖音评论助手" douyin_comment_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: douyin-comment-app
          path: dist/抖音评论助手.exe
